mysql:
- name: "default"
  username: "root"
  password: "mindy123"
  database: "egame"
  host: "127.0.0.1"
  port: 3306
  max_open_conn: 50
  max_idle_conn: 20
redis:
  addr: "localhost:6379"
  db: 5
  password: ""
session:
  session_name: "gosession_id"
base:
  host: 0.0.0.0
  port: 8091
  log_media: "redis"